version: "3.7"

services:
  jenkins:
    image: sixeyed/psod-pipelines-jenkins:20.04
    ports:
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    build:
      context: "20.04"


#version: "3.8"
#
#services:
#  jenkins:
#    image: jenkins/jenkins:lts
#    ports:
#    - "8080:8080"
#    volumes:
#    - /var/run/docker.sock:/var/run/docker.sock
